// Shared test constants. Values come from docs/FINDINGS.md §6 and are regenerated by
// scripts/gen-fixtures.ts; fixtures/vectors.json is the authoritative copy.
import { readFileSync } from 'node:fs';
import type { AccountState, Algorithm, Policy, Reason, Signer } from '../src/types.js';

export const SECP_SEED = 'sp5fV4UGhZhfCvcDRuY3dyyh5PjHf';
export const SECP_PUBLIC_KEY = '035A7FA22521397BE0FFE9CD7C35DDE0FB0C8EA96E48FF84E0C6309D0D4D70D9EA';
export const SECP_ADDRESS = 'rMPrYipfRHJryWfwYARAwhsVGvHwpUDjgA';

export const ED_SEED = 'sEdSKuYwxeL4JM1LBJcGmpLw9fbF8JN';
export const ED_PUBLIC_KEY = 'ED26D54D80051A116166CF76FEA87330D546680B875827B87AF1B1D58B9EB464E1';
export const ED_ADDRESS = 'rpjfAeE3DeeHPFnN2PgGFW5YxnZFAjrEyN';

/** An account that never signs anything in the fixtures. */
export const OTHER_ADDRESS = 'rGuN53T7cUp6Ec5L2tX9H7oJ7vQzVy6Cvq';

export const REFERENCE_MESSAGE = 'Sign in to example.com\nnonce: 0123456789abcdef';
export const REFERENCE_MESSAGE_HEX =
  '5369676E20696E20746F206578616D706C652E636F6D0A6E6F6E63653A2030313233343536373839616263646566';
export const SECP_REFERENCE_SIGNATURE =
  '30440220072BCE65E506246C591AD415313F091B89A3212C5EDA9E0205FC088C9A53FEA1022037FE519459B5FD6EEA039E15237755268646108639917618D51BE02724202A59';
/** Same r, s' = n - s. Mathematically valid, must be rejected as non_canonical_signature. */
export const SECP_REFERENCE_SIGNATURE_HIGH_S =
  '30450220072BCE65E506246C591AD415313F091B89A3212C5EDA9E0205FC088C9A53FEA1022100C801AE6BA64A029115FC61EADC88AAD83468CC6075B72A22EAB67E65AC1616E8';
export const ED_REFERENCE_SIGNATURE =
  '0FE0FACA05B234667E44A926553E1D06F93CCE82ECCD182233F1E420A8256229A01B28719C35B95CDAA2311609DB56F6B60C3F21CF10A5FC39A695775A63C300';

export const GEMWALLET_SECP_SEED = 'sn3nxiW7v8KXzPzAqzyHXbSSKNuN9';
export const GEMWALLET_ED_SEED = 'sEdSKaCy2JT7JaM7v95H9SxkhP9wS2r';
export const GEMWALLET_MESSAGE = 'Hello, XRPL! nonce=1234';

export const OFF_CURVE_PUBLIC_KEY = `02${'00'.repeat(31)}05`;
export const GENESIS_ADDRESS = 'rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh';

export const CHALLENGE_MEMO_TYPE = 'xrpl-message-verify/challenge/v1';

/** The hand-written v1 envelope used by the fixtures (domain example.com). */
export function envelopeExample(address: string): string {
  return [
    'example.com wants you to prove control of XRP Ledger account:',
    address,
    '',
    'Sign in to example.com',
    '',
    'URI: https://example.com/login',
    'Version: 1',
    'Network: testnet',
    'Nonce: 0123456789abcdef0123456789abcdef',
    'Issued At: 2026-09-04T00:00:00Z',
    'Expiration Time: 2026-09-04T00:10:00Z',
    'Request ID: 7c9e6679-7425-40de-944b-e07fc1f90ae7',
  ].join('\n');
}

export interface VectorExpect {
  valid: boolean;
  reason: Reason | null;
  signer: Signer;
  derivedAddress?: string;
}

export interface VectorOptions {
  expectedAccount?: string;
  expectedMemo?: string;
  allowMissingTransactionType?: boolean;
}

/** One record of fixtures/vectors.json. */
export interface Vector {
  id: string;
  source: string;
  kind: 'message' | 'signin';
  algorithm: Algorithm | null;
  encoding: 'utf8' | 'hex';
  message?: string;
  messageHex?: string;
  publicKey?: string;
  signature?: string;
  address?: string;
  blobHex?: string;
  options?: VectorOptions;
  account?: AccountState;
  policy?: Policy;
  expect: VectorExpect;
  notes: string;
}

export const VECTORS_URL = new URL('../../../fixtures/vectors.json', import.meta.url);
export const PENDING_DIR_URL = new URL('../../../fixtures/pending/', import.meta.url);

export function loadVectors(): Vector[] {
  const parsed = JSON.parse(readFileSync(VECTORS_URL, 'utf8')) as {
    version: number;
    vectors: Vector[];
  };
  if (parsed.version !== 1) throw new Error(`unexpected vectors.json version ${parsed.version}`);
  return parsed.vectors;
}
